/** Comprehensive AP course details — 39 courses, Chinese intros + textbooks */

export interface CourseDetail {
  short: string;
  intro_zh: string;
  exam_structure: string;
  topics: string[];
  prerequisites: string;
  difficulty_note: string;
  textbooks: { title: string; author?: string; publisher?: string; note?: string }[];
  study_resources: string[];
}

export const COURSE_DETAILS: Record<string, CourseDetail> = {
  // ══════ Mathematics ══════
  'CALC AB': { short:'CALC AB', intro_zh:'AP微积分AB是美国大学理事会开设的大学水平微积分入门课程，相当于大学第一学期的微积分课程。内容涵盖极限与连续性、导数及其应用、积分及其应用三大核心板块。作为中国学生最常选择的AP数学科目之一，微积分AB不仅是申请STEM专业的重要敲门砖，也是培养数学思维的关键课程。2024年全球约29万考生参加考试，5分率为21.4%。', exam_structure:'考试时长3小时15分钟，选择题45题(1小时45分钟，占50%)可使用图形计算器；自由作答题6题(1小时30分钟，占50%)。', topics:['极限与连续性','导数的定义与计算','导数的应用(极值、相关变化率)','积分与微积分基本定理','积分的应用(面积、体积)','微分方程初步'], prerequisites:'建议完成高中代数2和预备微积分课程，具备扎实的函数、三角学和代数基础。', difficulty_note:'难度中等偏高。中国学生因数学基础较好，通常觉得微积分AB的内容不难理解，但需要适应英文出题和答题方式。', textbooks:[{title:'Calculus: Early Transcendentals',author:'James Stewart',publisher:'Cengage',note:'最经典的大学微积分教材，内容远超AP要求'},{title:'Calculus for AP',author:'Ron Larson & Paul Battaglia',publisher:'Cengage',note:'专为AP设计的教材，习题与AP考试风格高度一致'},{title:'Calculus: Graphical, Numerical, Algebraic',author:'Finney, Demana, Waits, Kennedy',publisher:'Pearson',note:'AP教师最常用的课堂教材'},{title:"Barron's AP Calculus",publisher:"Barron's",note:'经典备考书'}], study_resources:['Khan Academy AP Calculus AB','College Board AP Classroom','AP Daily 视频课程'] },
  'CALC BC': { short:'CALC BC', intro_zh:'AP微积分BC是微积分AB的扩展版，内容涵盖AB的全部知识外加参数方程、极坐标、无穷级数等高级主题，相当于大学两个学期的微积分课程。2024年全球约13.5万考生，5分率高达47.7%。BC成绩优秀的学生通常可直接换取大学两个学期的微积分学分。', exam_structure:'与AB相同：选择题45题+自由作答题6题，共3小时15分钟。题目难度和范围更大。', topics:['AB全部内容','参数方程与极坐标','向量值函数','无穷级数与收敛性','泰勒级数与麦克劳林级数','反常积分'], prerequisites:'建议完成AP微积分AB或同等水平课程。数学基础扎实的学生可直接学习BC。', difficulty_note:'对于中国学生来说，BC的难度主要在于级数部分。5分率极高(47.7%)，因为考生通常数学基础较好。', textbooks:[{title:'Calculus: Early Transcendentals',author:'James Stewart',publisher:'Cengage'},{title:'Calculus for AP (Calc BC Edition)',author:'Ron Larson',publisher:'Cengage'},{title:"Barron's AP Calculus BC",publisher:"Barron's"}], study_resources:['Khan Academy AP Calculus BC','AP Classroom','Paul\'s Online Math Notes'] },
  'STATS': { short:'STATS', intro_zh:'AP统计学是一门应用广泛的大学水平统计入门课程，2024年全球约25万考生，5分率17.5%。与微积分不同，统计学更强调数据分析和逻辑推理，对中国学生来说，大量的英文阅读和写作是主要挑战。', exam_structure:'考试时长3小时。选择题40题(1.5小时，50%)，自由作答题6题(1.5小时，50%)含一道调查任务题。', topics:['数据收集与抽样方法','描述性统计与数据可视化','概率与随机变量','抽样分布与中心极限定理','置信区间','假设检验(t检验、卡方检验)','线性回归与相关分析'], prerequisites:'完成代数2即可，不需要微积分基础。但需要较强的英文阅读和逻辑推理能力。', difficulty_note:'中国学生通常觉得数学计算不难，但大量英文阅读、解释分析结果的写作部分是中国学生的薄弱环节。', textbooks:[{title:'The Practice of Statistics',author:'Starnes, Tabor, Yates, Moore',publisher:'Bedford, Freeman & Worth',note:'AP统计最权威教材'},{title:'Stats: Modeling the World',author:'Bock, Velleman, De Veaux',publisher:'Pearson'},{title:"Barron's AP Statistics",publisher:"Barron's"}], study_resources:['Khan Academy AP Statistics','Stats Medic','AP Classroom'] },
  'PRECALC': { short:'PRECALC', intro_zh:'AP预备微积分是2023-2024学年推出的最新AP数学课程，旨在为学生进入AP微积分做好准备。2024年首次考试即有约8万考生参加，5分率25.9%。', exam_structure:'考试时长3小时。选择题48题(2小时，63%)，自由作答题4题(1小时，37%)。', topics:['多项式与有理函数','指数与对数函数','三角函数与极坐标','参数方程与向量','矩阵初步','数列与级数入门'], prerequisites:'完成代数2课程。', difficulty_note:'作为AP新课程，内容难度适中。对于数学基础扎实的中国学生来说是较好的AP起点科目。', textbooks:[{title:'Precalculus: Mathematics for Calculus',author:'James Stewart',publisher:'Cengage'},{title:'Precalculus for AP',author:'Larson',publisher:'Cengage'}], study_resources:['Khan Academy Precalculus','AP Classroom'] },

  // ══════ Sciences ══════
  'BIO': { short:'BIO', intro_zh:'AP生物学是美国最受欢迎的AP科学课程之一，2024年全球约27万考生，5分率16.8%。课程强调科学探究和推理能力，而非单纯记忆大量事实。', exam_structure:'考试时长3小时。选择题60题(1.5小时，50%)，自由作答题6题(1.5小时，50%)含两道长答题和四道短答题。', topics:['生命化学基础','细胞结构与功能','细胞能量学','细胞通信与细胞周期','遗传学与基因表达','进化论与自然选择','生态学'], prerequisites:'建议完成高中生物和化学课程。需要较强的科学阅读和数据分析能力。', difficulty_note:'中国学生需要适应AP生物强调"解释和论证"而非"背诵"的考试风格。英文术语量较大。', textbooks:[{title:'Campbell Biology (AP Edition)',author:'Reece, Urry, Cain',publisher:'Pearson',note:'AP生物圣经级教材'},{title:'Biology for AP Courses',publisher:'OpenStax',note:'免费开源教材'},{title:"Barron's AP Biology",publisher:"Barron's"}], study_resources:['Bozeman Science AP Biology','Khan Academy AP Biology','AP Classroom'] },
  'CHEM': { short:'CHEM', intro_zh:'AP化学是大学水平化学入门课程，2024年全球约14万考生，5分率17.9%。课程特别强调实验探究和基于模型的推理。中国学生因国内化学教育基础扎实，通常表现较好。', exam_structure:'考试时长3小时15分钟。选择题60题(1.5小时，50%)，自由作答题7题(1小时45分钟，50%)。', topics:['原子结构与周期律','化学键与分子结构','化学反应与化学计量','热力学','化学动力学','化学平衡','酸碱与缓冲溶液','电化学'], prerequisites:'建议完成高中化学和代数2。', difficulty_note:'中国学生通常觉得AP化学的计算部分不难(比国内高考简单)，但实验设计和数据分析类题目需要额外练习。', textbooks:[{title:'Chemistry: The Central Science (AP Edition)',author:'Brown, LeMay, Bursten',publisher:'Pearson',note:'最经典的AP化学教材'},{title:'Chemistry for AP Courses',publisher:'OpenStax',note:'免费开源'},{title:"Barron's AP Chemistry",publisher:"Barron's"}], study_resources:['Khan Academy AP Chemistry','AP Classroom','Bozeman Science Chemistry'] },
  'PHYS 1': { short:'PHYS 1', intro_zh:'AP物理1是所有AP科目中通过率最低的科目之一，2024年仅47.3%考生获得3分及以上，5分率仅10.2%。课程以代数为基础，涵盖力学、波和基础电路。挑战在于考试极其强调实验设计和推理论证。', exam_structure:'考试时长3小时。选择题50题(1.5小时，50%)，自由作答题5题(1.5小时，50%)含实验设计题。', topics:['运动学','动力学(牛顿定律)','圆周运动与万有引力','能量','动量','简谐运动','转动运动','机械波与声学','基础电路'], prerequisites:'完成代数2，建议同步学习预备微积分。不需要微积分基础。', difficulty_note:'⚠️ AP最难的科目之一。实验设计和推理论证题是中国学生的主要失分点。建议充分备考。', textbooks:[{title:'College Physics (AP Edition)',author:'Serway & Vuille',publisher:'Cengage'},{title:"5 Steps to a 5: AP Physics 1",publisher:'McGraw-Hill',note:'策略导向备考'}], study_resources:['Flipping Physics YouTube','Khan Academy AP Physics 1','AP Classroom'] },
  'PHYS 2': { short:'PHYS 2', intro_zh:'AP物理2是物理1的后续课程，2024年约2.8万考生，5分率19.1%。内容涵盖流体力学、热力学、电磁学、光学和现代物理。', exam_structure:'与物理1相同的考试结构：选择题50题+自由作答题5题。', topics:['流体力学','热力学','电场与电势','电路(进阶)','磁学与电磁感应','光学','量子物理与核物理入门'], prerequisites:'完成AP物理1或同等水平课程。', difficulty_note:'参加人数较少(2.8万)，5分率比物理1高(19.1%)，因为考生通常已有物理1基础。', textbooks:[{title:'College Physics (AP Edition)',author:'Serway & Vuille',publisher:'Cengage'},{title:'University Physics',author:'Young & Freedman',publisher:'Pearson'}], study_resources:['Khan Academy','AP Classroom','Flipping Physics'] },
  'PHYS C:M': { short:'PHYS C:M', intro_zh:'AP物理C：力学是用微积分方法研究经典力学的大学水平课程，2024年约5.5万考生，5分率28.5%。适合对物理和工程有浓厚兴趣的学生。', exam_structure:'考试时长1.5小时。选择题35题(45分钟，50%)，自由作答题3题(45分钟，50%)。', topics:['运动学(微积分描述)','牛顿力学(含空气阻力)','功、能量与功率','动量系统','转动运动与角动量','简谐运动与引力'], prerequisites:'必须同步或已完成微积分课程。', difficulty_note:'需要有微积分基础，但5分率较高(28.5%)，适合数理功底扎实的中国学生。', textbooks:[{title:'University Physics',author:'Young & Freedman',publisher:'Pearson',note:'物理C最经典教材'},{title:'Fundamentals of Physics',author:'Halliday, Resnick, Walker',publisher:'Wiley'}], study_resources:['MIT OpenCourseWare Physics','AP Classroom','Flipping Physics C'] },
  'PHYS C:E&M': { short:'PHYS C:E&M', intro_zh:'AP物理C：电磁学用微积分方法研究电磁现象，2024年约2.5万考生，5分率高达35.2%。是一门高含金量但难度较大的课程。', exam_structure:'与力学相同：选择题35题+自由作答题3题，共1小时30分钟。', topics:['静电学(高斯定律)','导体与电容器','电路分析','磁场','电磁感应(法拉第定律)'], prerequisites:'必须完成或同步学习微积分。建议先修AP物理C：力学。', difficulty_note:'5分率最高之一(35.2%)，因为通常只有物理最强的学生才选择这门课。', textbooks:[{title:'University Physics',author:'Young & Freedman',publisher:'Pearson'},{title:'Introduction to Electrodynamics',author:'Griffiths',publisher:'Cambridge',note:'经典但偏难'}], study_resources:['MIT OCW Electricity & Magnetism','AP Classroom'] },
  'ENVIRO SCI': { short:'ENVIRO SCI', intro_zh:'AP环境科学是跨学科课程，融合生物学、化学、地理和社科。2024年约19万考生，5分率仅9.2%，通过率54.1%，是难度较大的AP科目之一。', exam_structure:'考试时长3小时。选择题80题(1.5小时，60%)，自由作答题3题(1小时10分钟，40%)。', topics:['生态系统','生物多样性','人口','地球系统与资源','能源与消耗','污染','全球变化'], prerequisites:'完成高中生物和化学课程。', difficulty_note:'考生常低估这门课。需要综合应用多学科知识，并大量阅读分析环境问题。', textbooks:[{title:'Environmental Science for AP',author:'Andrew Friedland & Rick Relyea',publisher:'Bedford, Freeman & Worth',note:'AP环境科学指定教材'},{title:"Barron's AP Environmental Science",publisher:"Barron's"}], study_resources:['Khan Academy','AP Environmental Science YouTube','Bozeman Science'] },

  // ══════ English ══════
  'ENG LANG': { short:'ENG LANG', intro_zh:'AP英语语言与写作是最大的AP科目——2024年近60万考生，但5分率仅9.8%，通过率54.6%。课程重点是非虚构文本分析和议论文写作，对中国学生来说是最具挑战的AP文科课程之一。', exam_structure:'考试时长3小时15分钟。选择题45题(1小时，45%)，作文3篇(2小时15分钟，55%)：综合写作、修辞分析、议论文。', topics:['修辞分析','论证结构拆解','论据与推理有效性','文体与风格','综合信息写作','议论文构建'], prerequisites:'需要较强的英语读写能力。建议托福100+或雅思7.0+。', difficulty_note:'中国学生最大的文科挑战。5分率仅9.8%，需要在英文阅读速度和写作质量上有极大投入。', textbooks:[{title:"The Language of Composition",author:'Shea, Scanlon, Aufses',publisher:"Bedford/St. Martin's",note:'AP英语语言指定教材'},{title:"CliffsNotes AP English Language",publisher:'CliffsNotes'}], study_resources:['College Board AP Daily Videos','Khan Academy Grammar','Purdue OWL Writing Lab'] },
  'ENG LIT': { short:'ENG LIT', intro_zh:'AP英语文学与写作专注于小说、诗歌和戏剧分析，2024年约39万考生，5分率13.7%。需要阅读大量经典文学作品并撰写文学分析论文。', exam_structure:'考试时长3小时。选择题55题(1小时，45%)，作文3篇(2小时，55%)：诗歌分析、散文分析、开放主题文学论证。', topics:['文学作品分析','诗歌解读','叙事技巧与视点','象征与隐喻','文学批评理论入门','比较文学分析'], prerequisites:'需要极强的英语阅读和文学分析能力。', difficulty_note:'对中国学生而言比AP英语语言更难，因为需要大量西方文学背景知识。', textbooks:[{title:"Literature & Composition",author:'Jago, Shea, Scanlon, Aufses',publisher:"Bedford/St. Martin's"},{title:"Barron's AP English Literature",publisher:"Barron's"}], study_resources:['AP Daily','LitCharts','SparkNotes'] },

  // ══════ History ══════
  'US HISTORY': { short:'US HISTORY', intro_zh:'AP美国历史是第二受欢迎的AP科目，2024年全球约49万考生，5分率12.8%。课程涵盖从1491年至今的美国历史。对中国学生来说，挑战在于巨大的阅读量和需要熟悉大量美国历史文化背景。', exam_structure:'考试时长3小时15分钟。选择题55题(55分钟，40%)，短答题3题(40分钟，20%)，DBQ文献题1题(60分钟，25%)，长篇论述题1题(40分钟，15%)。', topics:['殖民时期(1491-1763)','美国独立与建国','内战与重建','工业化与进步时代','两次世界大战与美国崛起','冷战与民权运动','当代美国(1980至今)'], prerequisites:'建议有一定美国历史基础知识，英语阅读能力需达到托福95+。', difficulty_note:'DBQ(文献分析题)是中国学生最头疼的题型，需要用历史文献证据支撑论文论点。', textbooks:[{title:"America's History (AP Edition)",author:'Henretta, Hinderaker, Edwards, Self',publisher:"Bedford/St. Martin's",note:'AP美国历史最常用教材'},{title:'The American Pageant',author:'Kennedy, Cohen',publisher:'Cengage'},{title:'AMSCO AP US History',publisher:'Perfection Learning',note:'备考精要，非常实用'}], study_resources:["Heimler's History YouTube",'Khan Academy APUSH','AP Classroom'] },
  'WORLD HIST': { short:'WORLD HIST', intro_zh:'AP世界历史(现代)涵盖从1200年至今的全球历史，2024年约38万考生，5分率11.9%。比AP美国历史更全球化，但因时间跨度大，信息量大。', exam_structure:'与美国历史相同的考试结构：选择题+短答题+DBQ+长篇论述题。', topics:['全球贸易网络(1200-1450)','帝国与跨文化交流','工业革命与全球化','20世纪冲突与变革','去殖民化','全球化时代'], prerequisites:'有高中历史基础知识即可，但建议英语阅读能力达托福90+。', difficulty_note:'覆盖面极广(800年全球史)，需要掌握大量信息并能进行跨区域比较分析。', textbooks:[{title:'Worlds Together, Worlds Apart',author:'Pollard, Rosenberg, Tignor',publisher:'Norton'},{title:'Ways of the World',author:'Robert Strayer',publisher:"Bedford/St. Martin's"},{title:'AMSCO AP World History',publisher:'Perfection Learning'}], study_resources:["Heimler's History",'Khan Academy','Freeman-pedia'] },
  'EURO HIST': { short:'EURO HIST', intro_zh:'AP欧洲历史覆盖1450年至今的欧洲政治、经济、文化与社会发展。2024年约8.5万考生，5分率13.1%。', exam_structure:'同一格式：选择55题+短答3题+DBQ+长论文。', topics:['文艺复兴与宗教改革','启蒙运动与科学革命','法国大革命与拿破仑','工业革命','民族主义与帝国主义','两次世界大战','冷战与欧洲一体化'], prerequisites:'建议有世界历史基础知识。', difficulty_note:'内容比世界史更聚焦，但需要深入理解欧洲思想史。', textbooks:[{title:"A History of Western Society (AP Edition)",author:'McKay, Crowston, Wiesner-Hanks',publisher:"Bedford/St. Martin's"}], study_resources:['AP Classroom','Tom Richey YouTube',"Heimler's History"] },
  'US GOV': { short:'US GOV', intro_zh:'AP美国政府与政治是增长最快的AP科目之一，2024年约31.6万考生，5分率24.3%(相比2023年的12.8%几乎翻倍)。研究美国政治制度、宪法基础和政治行为。', exam_structure:'考试时长3小时。选择题55题(1小时20分钟，50%)，自由作答题4题(1小时40分钟，50%)。', topics:['宪法基础','政治信仰与行为','政党与利益集团','国会、总统与法院','公民自由与民权','公共政策'], prerequisites:'建议有一定的美国政治常识基础。', difficulty_note:'2024年5分率大幅提升至24.3%，可能与考试改革有关。需要大量阅读案例分析。', textbooks:[{title:'American Government: Institutions and Policies (AP Edition)',author:'Wilson, DiIulio, Bose',publisher:'Cengage'},{title:'AMSCO AP US Government',publisher:'Perfection Learning'}], study_resources:["Heimler's History",'Khan Academy','AP Classroom'] },
  'COMP GOV': { short:'COMP GOV', intro_zh:'AP比较政府与政治是比较分析英国、俄罗斯、中国、墨西哥、伊朗和尼日利亚六国政治制度的AP课程。2024年约2.4万考生，5分率16.0%。', exam_structure:'考试时长2.5小时。选择题55题(1小时，50%)，自由作答题4题(1.5小时，50%)。', topics:['政治体系比较','政治文化与社会化','政治参与与选举','国家机构比较','公共政策','全球化与主权'], prerequisites:'无特定前置要求。对政治制度比较感兴趣即可。', difficulty_note:'中国学生可能对中国政治体系比较熟悉，但对其他五国政治制度需要从头学习。', textbooks:[{title:'Comparative Politics Today (AP Edition)',author:'Powell, Dalton, Strom',publisher:'Pearson'}], study_resources:['AP Classroom','C-SPAN Classroom'] },
  'HUMAN GEO': { short:'HUMAN GEO', intro_zh:'AP人文地理研究人类活动与地理环境的关系，2024年约26万考生，5分率17.9%。通常被9-10年级学生选为第一门AP课程。', exam_structure:'考试时长2小时15分钟。选择题60题(1小时，50%)，自由作答题3题(1小时15分钟，50%)。', topics:['地理思维与空间分析','人口与移民','文化模式','政治地理','农业与农村','城市与城市化','工业与经济发展'], prerequisites:'无前置要求，适合9-10年级入门。', difficulty_note:'内容广泛但深度较浅，适合作为AP入门。但27%的考生得1分，说明很多学生准备不足。', textbooks:[{title:'Human Geography for the AP Course',author:'Hildebrant, Lu, ZumBrunnen',publisher:"Bedford/St. Martin's"},{title:'AMSCO AP Human Geography',publisher:'Perfection Learning'}], study_resources:['Khan Academy','AP Classroom','Mr. Sinn YouTube'] },
  'AFAM STUDIES': { short:'AFAM STUDIES', intro_zh:'AP非裔美国人研究是2023年新推出的AP课程，2024年约1.5万考生，5分率14.2%。课程涵盖非洲裔美国人的历史、文化、文学和政治贡献，从非洲古代文明讲起一直到当代。', exam_structure:'考试时长3小时。选择题60题(1小时，50%)，自由作答题4题(2小时，50%)。', topics:['非洲文明起源','奴隶制与跨大西洋贸易','解放与重建','哈莱姆文艺复兴','民权运动','当代非裔美国人文化与政治'], prerequisites:'无特定前置要求。建议有一定美国历史基础。', difficulty_note:'作为较新的AP课程，教师资源相对有限。但课程内容深度和广度都很有价值。', textbooks:[{title:'AP African American Studies Course Framework',publisher:'College Board'}], study_resources:['AP Classroom','National Museum of African American History'] },

  // ══════ Social Sciences ══════
  'PSYCH': { short:'PSYCH', intro_zh:'AP心理学是一门非常受欢迎的入门级AP课程，2024年约32万考生，5分率19.2%。内容广泛但不深，涵盖从生物学基础到社会心理学的方方面面，是很多中国学生进入AP体系的"第一门课"。', exam_structure:'考试时长2小时。选择题100题(1小时10分钟，67%)，自由作答题2题(50分钟，33%)。', topics:['心理学历史与方法论','生物心理学','感觉与知觉','学习与认知','发展心理学','动机与情绪','人格理论','心理障碍与治疗','社会心理学'], prerequisites:'无特定前置要求，适合9-10年级学生。', difficulty_note:'最"友好"的AP科目之一。内容广泛但深度适中，英文词汇量大但都是实用词汇。', textbooks:[{title:"Myers' Psychology for AP",author:'David G. Myers',publisher:'Worth Publishers',note:'AP心理最权威教材，几乎人手一本'},{title:"Barron's AP Psychology",publisher:"Barron's"}], study_resources:['Crash Course Psychology YouTube','Khan Academy','Quizlet AP Psychology'] },
  'MACRO ECON': { short:'MACRO ECON', intro_zh:'AP宏观经济学研究国家层面的经济运行，2024年约14.5万考生，5分率20.7%。是中国学生最喜欢的AP社科科目之一，因为概念逻辑性强，计算适中。', exam_structure:'考试时长2小时10分钟。选择题60题(1小时10分钟，67%)，自由作答题3题(1小时，33%)。', topics:['基本经济概念','国民经济核算(GDP)','失业与通货膨胀','总需求-总供给模型','财政政策与货币政策','菲利普斯曲线','经济增长','国际贸易与金融'], prerequisites:'代数基础即可。', difficulty_note:'中国学生普遍觉得难度适中，图表分析和政策逻辑是考试重点。', textbooks:[{title:"Krugman's Economics for AP",author:'Paul Krugman',publisher:'Worth Publishers',note:'诺贝尔奖得主编写的AP经济教材'},{title:"Barron's AP Macroeconomics",publisher:"Barron's"}], study_resources:['ACDC Econ YouTube (Jacob Clifford)','Khan Academy','AP Classroom'] },
  'MICRO ECON': { short:'MICRO ECON', intro_zh:'AP微观经济学研究个体经济决策，2024年约10万考生，5分率22.9%。内容与日常生活紧密相关，中国学生通常觉得较容易上手。', exam_structure:'与宏观相同：选择题60题+自由作答题3题。', topics:['供求模型','弹性','消费者选择理论','生产成本与市场结构','完全竞争与垄断','博弈论入门','劳动力市场','市场失灵与政府干预'], prerequisites:'代数基础即可，与宏观无先后关系。', difficulty_note:'比宏观更直观，因为涉及的是微观层面的经济学概念，与现实生活紧密相关。', textbooks:[{title:"Krugman's Economics for AP",author:'Paul Krugman',publisher:'Worth Publishers'},{title:"Barron's AP Microeconomics",publisher:"Barron's"}], study_resources:['ACDC Econ','Khan Academy','Marginal Revolution University'] },

  // ══════ Computer Science ══════
  'CS A': { short:'CS A', intro_zh:'AP计算机科学A是使用Java语言的大学水平编程入门课程，2024年约9.5万考生，5分率25.6%。强调面向对象编程和算法设计，是STEM方向学生的热门选择。', exam_structure:'考试时长3小时。选择题40题(1.5小时，50%)，自由作答题4题(1.5小时，50%)，需手写Java代码。', topics:['基本编程概念与Java语法','类与对象(面向对象编程)','数组与ArrayList','继承与多态','递归','排序与搜索算法'], prerequisites:'无编程基础要求，但逻辑思维能力强的学生更容易上手。', difficulty_note:'中国学生通常编程上手较快，但需要大量练习手写代码(考试时需在纸上写正确Java代码，不能调试)。', textbooks:[{title:'Java Methods: Object-Oriented Programming and Data Structures',author:'Litvin & Litvin',publisher:'Skylight Publishing',note:'AP CS A最常用教材'},{title:"Barron's AP Computer Science A",publisher:"Barron's"}], study_resources:['CodeHS AP Java','CodingBat Java Practice','AP Classroom','Runestone Academy'] },
  'CS PRINCIPLES': { short:'CS PRINCIPLES', intro_zh:'AP计算机科学原理是更注重计算机科学通识的课程，2024年约17万考生，5分率10.9%。包括一个Create Performance Task(创建任务)，不需要特定编程语言。', exam_structure:'选择题70题(2小时，70%)+ Create Performance Task(课外完成，30%)。', topics:['计算机与互联网基础','数据与信息','算法与编程基础','网络安全','计算的影响(社会、伦理)'], prerequisites:'不需要编程背景。', difficulty_note:'比CS A简单，适合探索计算机科学兴趣。但5分率较低(10.9%)，因为考试包含大量阅读理解题。', textbooks:[{title:'Computer Science Principles: The Foundational Concepts',author:'Kevin Hare'},{title:"Barron's AP Computer Science Principles",publisher:"Barron's"}], study_resources:['Code.org AP CSP','Khan Academy','AP Classroom'] },

  // ══════ World Languages ══════
  'CHINESE LANG': { short:'CHINESE LANG', intro_zh:'AP中文语言与文化是5分率最高的AP科目——2024年高达53.3%。测试听说读写四项技能，以中文为母语的学生有天然优势。但需注意：母语者也需要熟悉考试格式和文化内容要求。', exam_structure:'计算机化考试。选择题+自由作答题，包含听力、阅读、写作和口语四部分。', topics:['家庭与社会','科技与日常生活','传统文化与当代社会','全球化与挑战'], prerequisites:'建议中文水平达到中级以上。', difficulty_note:'对于有中文背景的学生是最容易拿5分的科目之一。但非母语者难度较大。', textbooks:[{title:"Barron's AP Chinese Language",publisher:"Barron's"},{title:'Integrated Chinese',publisher:'Cheng & Tsui'}], study_resources:['AP Classroom','ChinesePod','Du Chinese'] },
  'JAPANESE LANG': { short:'JAPANESE LANG', intro_zh:'AP日语语言与文化是5分率第二高的AP科目(49.1%)，但考生极少(约3000人)。多数考生有日语母语背景。', exam_structure:'计算机化考试，测试听说读写四项技能。', topics:['日本家庭与社会','科技与生活','传统文化与当代日本','全球议题'], prerequisites:'建议日语达到中高级水平(JLPT N3以上)。', difficulty_note:'适合有日语背景的学生。非母语者需要多年系统学习。', textbooks:[{title:"Barron's AP Japanese Language",publisher:"Barron's"},{title:'Genki: An Integrated Course in Elementary Japanese',publisher:'The Japan Times'}], study_resources:['AP Classroom','WaniKani','Tae Kim\'s Guide to Japanese'] },
  'SPAN LANG': { short:'SPAN LANG', intro_zh:'AP西班牙语语言与文化是最大的外语AP科目，2024年约17万考生，5分率21.2%。目标是达到中高级西班牙语水平。', exam_structure:'约3小时。含人际沟通、解释性沟通和表达性沟通三种模式。', topics:['家庭与社区','科技与自我','美与美学','科学与伦理','全球化挑战'], prerequisites:'建议已完成3-4年西班牙语学习。', difficulty_note:'对于从零开始的中国学生难度很大，需要持续投入。', textbooks:[{title:'Temas: AP Spanish Language and Culture',publisher:'Vista Higher Learning'},{title:'AP Spanish: Preparing for the Language Exam',publisher:'Pearson'}], study_resources:['AP Classroom','Duolingo Spanish','SpanishDict'] },
  'SPAN LIT': { short:'SPAN LIT', intro_zh:'AP西班牙文学与文化专注于西班牙语文学经典作品的分析与解读，2024年约2.5万考生，5分率10.2%。', exam_structure:'考试约3小时，含选择题和自由作答题。', topics:['中世纪与文艺复兴文学','黄金世纪','19世纪文学','20世纪及当代文学','拉丁美洲文学'], prerequisites:'需要高级西班牙语水平。通常先修AP西班牙语语言。', difficulty_note:'需要深度阅读和分析西班牙语文学作品，难度较大。', textbooks:[{title:'Azulejo: Anthology & Guide to the AP Spanish Literature Course',publisher:'Wayside Publishing'}], study_resources:['AP Classroom','Biblioteca Virtual Miguel de Cervantes'] },
  'FRENCH LANG': { short:'FRENCH LANG', intro_zh:'AP法语语言与文化测试中级到高级法语水平，2024年约2.1万考生，5分率14.5%。', exam_structure:'约3小时，测试听说读写四项。', topics:['家庭与社会','科技与日常生活','文化美学','全球议题'], prerequisites:'建议3-4年法语学习基础。', difficulty_note:'法语语法体系对英语学习者有一定挑战。', textbooks:[{title:'Thèmes: AP French Language and Culture',publisher:'Vista Higher Learning'},{title:"Barron's AP French",publisher:"Barron's"}], study_resources:['AP Classroom','TV5Monde','RFI Savoirs'] },
  'GERMAN LANG': { short:'GERMAN LANG', intro_zh:'AP德语语言与文化测试中高级德语水平，2024年约5000考生，5分率26.1%。', exam_structure:'约3小时，测试听说读写四项。', topics:['家庭与社会','科技与生活','文化与传统','全球挑战'], prerequisites:'建议3-4年德语学习基础。', difficulty_note:'德语语法体系较为复杂，但5分率较高(26.1%)。', textbooks:[{title:"Barron's AP German Language",publisher:"Barron's"}], study_resources:['AP Classroom','Deutsche Welle','Goethe-Institut'] },
  'ITALIAN LANG': { short:'ITALIAN LANG', intro_zh:'AP意大利语言与文化2024年约3000考生，5分率22.6%。是最小规模的AP外语科目之一。', exam_structure:'约3小时，测试听说读写四项。', topics:['家庭与社区','科技与日常生活','文化遗产','全球议题'], prerequisites:'建议3-4年意大利语学习基础。', difficulty_note:'考生规模极小，通常由意裔学生或有浓厚兴趣的学生选修。', textbooks:[{title:"Barron's AP Italian Language",publisher:"Barron's"}], study_resources:['AP Classroom','Rai Cultura','Italiano Automatico'] },
  'LATIN': { short:'LATIN', intro_zh:'AP拉丁语是最具挑战的AP外语科目，2024年约5000考生，通过率仅56.5%，5分率11.9%。学生需翻译维吉尔《埃涅阿斯纪》和凯撒《高卢战记》选段。', exam_structure:'考试时长3小时。含翻译题、阅读分析题和论述题。', topics:['拉丁语语法与句法','维吉尔《埃涅阿斯纪》','凯撒《高卢战记》','罗马文化与历史','修辞手法分析'], prerequisites:'需要3-4年拉丁语学习基础。', difficulty_note:'通过率最低的外语AP之一。需要大量记忆词汇和语法规则。', textbooks:[{title:'Latin for the New Millennium',publisher:'Bolchazy-Carducci'},{title:'Wheelock\'s Latin',author:'Frederic M. Wheelock',publisher:'HarperCollins'}], study_resources:['AP Classroom','The Latin Library','Whitaker\'s Words'] },

  // ══════ Arts ══════
  'ART HIST': { short:'ART HIST', intro_zh:'AP艺术史覆盖从史前到当代的全球艺术发展，2024年约2.6万考生，通过率62.7%，5分率13.9%。学生需识别250件核心艺术作品，并能进行视觉分析与文化背景解读。', exam_structure:'考试时长3小时。选择题80题(1小时，50%)，自由作答题6题(2小时，50%)。', topics:['史前与古代近东艺术','古希腊与罗马','亚洲、非洲与美洲艺术','中世纪与拜占庭','文艺复兴','巴洛克与洛可可','19-20世纪现代艺术','当代艺术'], prerequisites:'无前置要求，但需要较强的视觉记忆和写作能力。', difficulty_note:'最大的挑战是记忆250件指定作品的详细信息（作者、年代、材料、风格、文化意义）。', textbooks:[{title:"Gardner's Art Through the Ages (AP Edition)",author:'Kleiner',publisher:'Cengage'},{title:"Barron's AP Art History",publisher:"Barron's"}], study_resources:['Smarthistory/Khan Academy','AP Classroom','Google Arts & Culture'] },
  'MUSIC THEO': { short:'MUSIC THEO', intro_zh:'AP音乐理论是大学水平的音乐理论与分析入门课程，2024年约1.8万考生，通过率60.2%，5分率19.0%。包含听力测试(占45%)和笔试(占55%)。', exam_structure:'考试时长2小时40分钟。听力选择题+笔试选择题+自由作答题(含旋律听写、和声分析等)。', topics:['音程与和弦','和声进行','声部进行','曲式分析','旋律与节奏听写','视唱'], prerequisites:'建议有一定的音乐基础(如能识五线谱、了解基本音程概念)。', difficulty_note:'听力测试部分对非母语者有一定挑战。有乐器基础的学生通常表现更好。', textbooks:[{title:"The Musician's Guide to Theory and Analysis",author:'Clendinning & Marvin',publisher:'Norton'},{title:"Barron's AP Music Theory",publisher:"Barron's"}], study_resources:['AP Classroom','musictheory.net','Teoria'] },
  'STUDIO 2D': { short:'STUDIO 2D', intro_zh:'AP工作室艺术：平面设计是提交作品集而非笔试的艺术AP课程，2024年约3.4万考生，通过率82.8%。学生需提交15件作品组成的Sustained Investigation作品集。', exam_structure:'无传统笔试。提交Sustained Investigation作品集(15件作品)，包含作品图像、过程说明和书面分析。', topics:['构图原则','色彩理论','视觉传达','材料与技巧','概念发展','艺术批评'], prerequisites:'建议有1-2年艺术创作基础。', difficulty_note:'需要大量课外时间创作作品集。对时间管理和独立创作能力要求较高。', textbooks:[{title:'AP Studio Art: Course and Exam Description',publisher:'College Board'}], study_resources:['AP Classroom','College Board AP Art Portfolios Gallery'] },
  'STUDIO 3D': { short:'STUDIO 3D', intro_zh:'AP工作室艺术：立体设计专注于三维空间中的艺术创作，2024年约8000考生，通过率72.0%。提交包含15件三维作品的Sustained Investigation作品集。', exam_structure:'无笔试。提交Sustained Investigation作品集(15件立体作品)。', topics:['空间关系','体量与形式','材料探索','结构完整性','功能与美学','概念表达'], prerequisites:'建议有造型艺术基础。', difficulty_note:'材料成本和工作室空间是主要限制因素。', textbooks:[{title:'AP Studio Art: Course and Exam Description',publisher:'College Board'}], study_resources:['AP Classroom','College Board AP Art Portfolios'] },
  'STUDIO DRAW': { short:'STUDIO DRAW', intro_zh:'AP工作室艺术：绘画专注于各种媒介的绘画创作，2024年约2.2万考生，通过率83.8%。提交包含15件绘画作品的Sustained Investigation作品集。', exam_structure:'无笔试。提交Sustained Investigation作品集(15件绘画作品)。', topics:['线条与标记','光影与色调','色彩运用','构图与空间','材料实验','个人风格发展'], prerequisites:'建议有绘画基础。', difficulty_note:'通过率最高的艺术AP之一(83.8%)，但需要大量时间和精力进行创作。', textbooks:[{title:'AP Studio Art: Course and Exam Description',publisher:'College Board'}], study_resources:['AP Classroom','College Board AP Art Portfolios','Drawspace'] },

  // ══════ Capstone ══════
  'SEMINAR': { short:'SEMINAR', intro_zh:'AP研讨课是AP Capstone文凭项目的第一年课程，2024年约9万考生，通过率高达85.7%。课程培养学术研究、团队协作和演示能力。', exam_structure:'包括三项评估：团队项目与演示(20%)+ 个人研究论文(35%)+ 年终笔试(45%)。', topics:['论证分析','研究问题构建','多源信息评估','学术写作','团队协作','口头演示'], prerequisites:'无特定前置要求，但建议英语读写能力较强。', difficulty_note:'通过率最高(85.7%)，但高分(5分)率仅9.4%。大部分学生集中在3-4分。', textbooks:[{title:'AP Seminar: A Practical Guide',publisher:'College Board'}], study_resources:['AP Classroom','Purdue OWL','EBSCO Research Databases'] },
  'RESEARCH': { short:'RESEARCH', intro_zh:'AP研究课是AP Capstone第二年的课程，2024年约5.5万考生，通过率86.1%。学生需独立完成一篇4000-5000字的学术研究论文并进行答辩。', exam_structure:'全年项目：学术论文(75%)+ 口头答辩(25%)，无传统考试。', topics:['研究设计','文献综述','方法论选择','数据收集与分析','学术写作','口头答辩'], prerequisites:'必须完成AP研讨课。', difficulty_note:'通过率最高之一(86.1%)，但只适合真正有研究兴趣和自主驱动力的学生。', textbooks:[{title:'The Craft of Research',author:'Booth, Colomb, Williams',publisher:'University of Chicago Press'}], study_resources:['AP Classroom','Google Scholar','JSTOR'] },
};

export function getCourseDetail(short: string): CourseDetail | undefined {
  return COURSE_DETAILS[short];
}
